M48
; DRILL file {KiCad 9.0.4} date 2025-10-31T13:00:31+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-31T13:00:31+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.660
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.080
%
G90
G05
T1
X62.0Y-79.0
T2
X62.0Y-71.0
M30
